version: '3'
services:
  escrow:
    volumes:
    - ./Escrow/node.conf:/etc/corda/node.conf
    - ./Escrow/node.conf:/opt/corda/node.conf
    - ./Escrow/certificates:/opt/corda/certificates
    - ./Escrow/logs:/opt/corda/logs
    - ./Escrow/persistence:/opt/corda/persistence
    - ./Escrow/cordapps:/opt/corda/cordapps
    - ./Escrow/network-parameters:/opt/corda/network-parameters
    - ./Escrow/additional-node-infos:/opt/corda/additional-node-infos
    - ./Escrow/drivers:/opt/corda/drivers
    environment:
    - ACCEPT_LICENSE=${ACCEPT_LICENSE}
#    - CORDA_ARGS=run-migration-scripts --core-schemas --app-schemas
    ports:
    - "10005:10005"
    - "10006:10006"
    - "10046:10046"
    - "2221:2221"
    image: corda/corda-zulu-java1.8-4.6
  bob:
    volumes:
    - ./Bob/node.conf:/etc/corda/node.conf
    - ./Bob/node.conf:/opt/corda/node.conf
    - ./Bob/certificates:/opt/corda/certificates
    - ./Bob/logs:/opt/corda/logs
    - ./Bob/persistence:/opt/corda/persistence
    - ./Bob/cordapps:/opt/corda/cordapps
    - ./Bob/network-parameters:/opt/corda/network-parameters
    - ./Bob/additional-node-infos:/opt/corda/additional-node-infos
    - ./Bob/drivers:/opt/corda/drivers
    environment:
    - ACCEPT_LICENSE=${ACCEPT_LICENSE}
#    - CORDA_ARGS=run-migration-scripts --core-schemas --app-schemas
    ports:
    - "10012:10012"
    - "10013:10013"
    - "10014:10014"
    - "2223:2223"
    image: corda/corda-zulu-java1.8-4.6
